using System.Text;

namespace WcfNetTcpClientGenerator.Core;

public sealed class WrapperImplementationGenerator
{
    private readonly NullMethodDocumentationProvider _fallbackDocumentationProvider;

    public WrapperImplementationGenerator()
        : this(new NullMethodDocumentationProvider())
    {
    }

    public WrapperImplementationGenerator(NullMethodDocumentationProvider fallbackDocumentationProvider)
    {
        _fallbackDocumentationProvider = fallbackDocumentationProvider;
    }

    public async Task<GeneratedImplementationResult> GenerateAsync(
        WcfContractModel contract,
        string libraryNamespace,
        ClientLibraryGenerationOptions options,
        IMethodDocumentationProvider documentationProvider,
        CancellationToken cancellationToken)
    {
        var diagnostics = new List<GenerationDiagnostic>();
        var contractTypeName = CSharpIdentifierSanitizer.SanitizeTypeName(contract.ContractName);
        var interfaceName = $"I{contractTypeName}Client";
        var className = $"{contractTypeName}Client";

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        if (options.DocumentationOptions.UsesAiProvider)
        {
            builder.AppendLine("// XML documentation comments may have been AI-assisted.");
            builder.AppendLine("// Review generated comments for accuracy before publishing this package.");
        }
        builder.AppendLine($"using {libraryNamespace}.Binding;");
        builder.AppendLine($"using {libraryNamespace}.Interfaces;");
        builder.AppendLine($"using {libraryNamespace}.Options;");
        builder.AppendLine($"using ServiceReference = {contract.ProxyNamespace};");
        builder.AppendLine();
        builder.AppendLine($"namespace {libraryNamespace}.Services;");
        builder.AppendLine();
        builder.AppendLine($"public sealed class {className} : {interfaceName}");
        builder.AppendLine("{");
        builder.AppendLine("    private readonly NetTcpWcfClientOptions _options;");
        builder.AppendLine();
        builder.AppendLine($"    public {className}(NetTcpWcfClientOptions options)");
        builder.AppendLine("    {");
        builder.AppendLine("        _options = options ?? throw new global::System.ArgumentNullException(nameof(options));");
        builder.AppendLine("    }");
        builder.AppendLine();

        foreach (var operation in contract.Operations)
        {
            var documentationRequest = BuildDocumentationRequest(contract, operation);
            ReportProgress(options, DiagnosticSeverity.Info, BuildGenerationMessage(options.DocumentationOptions.ProviderKind, operation.MethodName));

            MethodDocumentationResult documentationResult;
            try
            {
                documentationResult = await documentationProvider.GenerateDocumentationAsync(
                    documentationRequest,
                    options.DocumentationOptions,
                    cancellationToken).ConfigureAwait(false);
            }
            catch (Exception exception)
            {
                diagnostics.Add(new GenerationDiagnostic(
                    DiagnosticSeverity.Warning,
                    $"Documentation provider failed for {operation.MethodName}; using fallback comment. {exception.Message}",
                    "DOCUMENTATION_PROVIDER_FAILED"));

                documentationResult = await _fallbackDocumentationProvider.GenerateDocumentationAsync(
                    documentationRequest,
                    options.DocumentationOptions,
                    cancellationToken).ConfigureAwait(false);
            }

            foreach (var documentationDiagnostic in documentationResult.Diagnostics)
            {
                diagnostics.Add(new GenerationDiagnostic(
                    ParseSeverity(documentationDiagnostic.Severity),
                    $"{operation.MethodName}: {documentationDiagnostic.Message}",
                    documentationDiagnostic.Code));
            }

            if (documentationResult.WasGeneratedByAi)
            {
                ReportProgress(options, DiagnosticSeverity.Info, BuildGeneratedMessage(options.DocumentationOptions.ProviderKind, operation.MethodName));
            }
            else
            {
                var fallbackCode = options.DocumentationOptions.ProviderKind == DocumentationProviderKind.OpenAI
                    ? "OPENAI_FALLBACK"
                    : "COPILOT_FALLBACK";

                var fallbackMessage = documentationResult.Diagnostics.Any(diagnostic => diagnostic.Code == fallbackCode)
                    ? BuildFailureMessage(options.DocumentationOptions.ProviderKind, operation.MethodName)
                    : $"Using fallback comment for {operation.MethodName}.";
                ReportProgress(options, DiagnosticSeverity.Warning, fallbackMessage);
            }

            builder.AppendLine(IndentDocumentation(documentationResult.XmlDocumentationText));
            builder.AppendLine(GenerateMethod(contract, operation));
        }

        builder.AppendLine(GenerateCloseMethod());
        builder.AppendLine("}");

        return new GeneratedImplementationResult(builder.ToString(), diagnostics);
    }

    private static MethodDocumentationRequest BuildDocumentationRequest(WcfContractModel contract, WcfOperationModel operation)
    {
        var returnType = operation.ResponseTypeName.Equals("void", StringComparison.Ordinal)
            ? "global::System.Threading.Tasks.Task"
            : $"global::System.Threading.Tasks.Task<{operation.ResponseTypeName}>";

        var parameters = new List<WcfParameterModel>(operation.Parameters)
        {
            new()
            {
                Name = "cancellationToken",
                TypeName = "global::System.Threading.CancellationToken"
            }
        };

        var methodSignature = $"{returnType} {operation.MethodName}({string.Join(", ", parameters.Select(static parameter => $"{parameter.TypeName} {parameter.Name}"))})";
        var requestTypeName = operation.Parameters.FirstOrDefault()?.TypeName ?? "None";

        return new MethodDocumentationRequest
        {
            ServiceName = contract.ContractName,
            OperationName = operation.OperationName,
            GeneratedWrapperMethodName = operation.MethodName,
            RequestTypeName = requestTypeName,
            ResponseTypeName = operation.ResponseTypeName,
            Parameters = parameters,
            ReturnType = returnType,
            FaultContracts = operation.FaultContracts,
            WcfBindingType = "NetTcpBinding",
            IsAsync = true,
            WsdlDocumentationText = operation.DocumentationText,
            GeneratedMethodSignature = methodSignature,
            SampleRequestTypeName = requestTypeName,
            SampleResponseTypeName = operation.ResponseTypeName
        };
    }

    private static void ReportProgress(ClientLibraryGenerationOptions options, DiagnosticSeverity severity, string message)
        => options.ProgressReporter?.Report(new GenerationDiagnostic(severity, message));

    private static DiagnosticSeverity ParseSeverity(string severity)
        => Enum.TryParse<DiagnosticSeverity>(severity, ignoreCase: true, out var parsed)
            ? parsed
            : DiagnosticSeverity.Info;

    private static string BuildGenerationMessage(DocumentationProviderKind providerKind, string methodName)
        => providerKind switch
        {
            DocumentationProviderKind.OpenAI => $"Generating OpenAI comment for {methodName}...",
            DocumentationProviderKind.Microsoft365Copilot => $"Generating Copilot comment for {methodName}...",
            _ => $"Generating comment for {methodName}..."
        };

    private static string BuildGeneratedMessage(DocumentationProviderKind providerKind, string methodName)
        => providerKind switch
        {
            DocumentationProviderKind.OpenAI => $"OpenAI comment generated for {methodName}.",
            DocumentationProviderKind.Microsoft365Copilot => $"Copilot comment generated for {methodName}.",
            _ => $"Comment generated for {methodName}."
        };

    private static string BuildFailureMessage(DocumentationProviderKind providerKind, string methodName)
        => providerKind switch
        {
            DocumentationProviderKind.OpenAI => $"OpenAI failed for {methodName}; using fallback comment.",
            DocumentationProviderKind.Microsoft365Copilot => $"Copilot failed for {methodName}; using fallback comment.",
            _ => $"Using fallback comment for {methodName}."
        };

    private static string IndentDocumentation(string xmlDocumentationText)
    {
        var lines = xmlDocumentationText
            .Split(["\r\n", "\n"], StringSplitOptions.None)
            .Select(static line => string.IsNullOrWhiteSpace(line) ? "    ///" : $"    {line.TrimEnd()}")
            .ToList();

        return string.Join(Environment.NewLine, lines);
    }

    private static string GenerateMethod(WcfContractModel contract, WcfOperationModel operation)
    {
        var returnType = operation.ResponseTypeName.Equals("void", StringComparison.Ordinal)
            ? "global::System.Threading.Tasks.Task"
            : $"global::System.Threading.Tasks.Task<{operation.ResponseTypeName}>";

        var parameters = operation.Parameters.Count == 0
            ? string.Empty
            : $"{string.Join(", ", operation.Parameters.Select(static parameter => $"{parameter.TypeName} {parameter.Name}"))}, ";

        var invocationParameters = string.Join(", ", operation.Parameters.Select(static parameter => parameter.Name));
        var invocation = string.IsNullOrWhiteSpace(invocationParameters)
            ? $"await client.{operation.ProxyMethodName}().ConfigureAwait(false);"
            : $"await client.{operation.ProxyMethodName}({invocationParameters}).ConfigureAwait(false);";

        if (!operation.ResponseTypeName.Equals("void", StringComparison.Ordinal))
        {
            invocation = string.IsNullOrWhiteSpace(invocationParameters)
                ? $"return await client.{operation.ProxyMethodName}().ConfigureAwait(false);"
                : $"return await client.{operation.ProxyMethodName}({invocationParameters}).ConfigureAwait(false);";
        }

        var builder = new StringBuilder();
        builder.AppendLine($"    public async {returnType} {operation.MethodName}({parameters}global::System.Threading.CancellationToken cancellationToken = default)");
        builder.AppendLine("    {");
        builder.AppendLine("        cancellationToken.ThrowIfCancellationRequested();");
        builder.AppendLine();
        builder.AppendLine("        var binding = NetTcpBindingFactory.Create(_options);");
        builder.AppendLine("        var endpointAddress = new global::System.ServiceModel.EndpointAddress(_options.EndpointUrl);");
        builder.AppendLine($"        var client = new ServiceReference.{contract.ClientClassName}(binding, endpointAddress);");
        builder.AppendLine();
        builder.AppendLine("        try");
        builder.AppendLine("        {");
        builder.AppendLine("            ApplyCredentials(client);");
        builder.Append("            ");
        builder.AppendLine(invocation);
        if (operation.ResponseTypeName.Equals("void", StringComparison.Ordinal))
        {
            builder.AppendLine("            CloseClient(client);");
            builder.AppendLine("            return;");
        }
        else
        {
            builder.AppendLine("        }");
            builder.AppendLine("        catch");
            builder.AppendLine("        {");
            builder.AppendLine("            client.Abort();");
            builder.AppendLine("            throw;");
            builder.AppendLine("        }");
            builder.AppendLine("        finally");
            builder.AppendLine("        {");
            builder.AppendLine("            if (client.State != global::System.ServiceModel.CommunicationState.Faulted)");
            builder.AppendLine("            {");
            builder.AppendLine("                CloseClient(client);");
            builder.AppendLine("            }");
            builder.AppendLine("        }");
            builder.AppendLine("    }");
            return builder.ToString();
        }

        builder.AppendLine("        }");
        builder.AppendLine("        catch");
        builder.AppendLine("        {");
        builder.AppendLine("            client.Abort();");
        builder.AppendLine("            throw;");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        return builder.ToString();
    }

    private static string GenerateCloseMethod()
        => """
    private static void CloseClient(global::System.ServiceModel.ICommunicationObject client)
    {
        try
        {
            if (client.State != global::System.ServiceModel.CommunicationState.Closed)
            {
                client.Close();
            }
        }
        catch
        {
            client.Abort();
            throw;
        }
    }

    private void ApplyCredentials<TChannel>(global::System.ServiceModel.ClientBase<TChannel> client)
        where TChannel : class
    {
        if (string.Equals(_options.TcpClientCredentialType, "UserName", global::System.StringComparison.OrdinalIgnoreCase)
            && !string.IsNullOrWhiteSpace(_options.Username)
            && !string.IsNullOrWhiteSpace(_options.Password))
        {
            client.ClientCredentials.UserName.UserName = _options.Username;
            client.ClientCredentials.UserName.Password = _options.Password;
        }
    }
""";

    public sealed record GeneratedImplementationResult(string Source, IReadOnlyList<GenerationDiagnostic> Diagnostics);
}
